version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch-latest
    environment:
      - cluster.name=hackathon
      - bootstrap.memory_lock=true
      - node.name=stretch_armstrong
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - xpack.monitoring.templates.enabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks:
      - esnet

  ki01:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana-latest
    hostname: kibana
    ports: [ '5601:5601' ]
    networks: [ 'esnet' ]
    depends_on: [ 'es01' ]
    restart: on-failure
    environment:
      - XPACK_MONITORING_ENABLED=true
      - ELASTICSEARCH_HOSTS=http://es01:9200

volumes:
  es-data:

networks:
  esnet: